### ISSUE TITLE
heatmap -- something went wrong

### ISSUE THREAD

**Issue by neuroBazzi** [MetaCell/salk-interactive-atlas#113]
Tried to load heatmap / cenotroids of a few populations but I get the error message

<img width="1072" alt="Screenshot 2022-05-16 at 12 22 19" src="https://user-images.githubusercontent.com/57769656/168638892-d08fc922-92f7-43cb-aa03-a17f96e52491.png">

**Comment by afonsobspinto** [comment]
@neuroBazzi can you replicate this in development?

**Comment by neuroBazzi** [comment]
no, this got solved with latest deploy
