### ISSUE TITLE
In the 2D viewer, the contours I added in were also included as populations.

### ISSUE THREAD

**Issue by neuroBazzi** [MetaCell/salk-interactive-atlas#187]
not sure how they added contours, I have asked for more information and snapshots

**Comment by neuroBazzi** [comment]
@afonsobspinto client says this refers to the PKD2L1 experiment, so the same dataset for which the was the 2D/3D registration mismatch. I am not sure this is something you will be able to solve or rather it is for Stephen Lenzi. IF you can share any thought it would be helpful

_I added a contour to remove false detections in one of the channels for the PKD2L1 Cord. This contour is labeled in the key file as L10Keep. I don't know how the data is uploaded to the atlas, but in every data file, for every point and contour, there is a column that is either "isPoint" or "isContour" with a value of 1 or 0 (if there is a 1 in "isContour", then it is a contour, and vice versa). I was under the impression that all datasets that are positive for "isContour" are not loaded as data into the atlas._

**Comment by afonsobspinto** [comment]
Seems to be something for Stephen. We have no word in the filtering of isPoint or isContour, we only receive coordinates x,y,z which we treat as cells.
