### ISSUE TITLE
Stage environment

### ISSUE THREAD

**Issue by neuroBazzi** [MetaCell/salk-interactive-atlas#188]
@zsinnema I noticed that on Stage there is still some mismatch between the 2D and 3D viewers (see image), I thought @afonsobspinto fixed this, is it possible that this is because there is an version on stage that does not have the latest fix? if so, could we bring stage up to dev (minus the latest features Afonso is working on this week) by sprint meeting tomorrow?
To be clear: the issue with the image below is that neurons (the pink balls) are within the 3d mesh in the 3d viewer (which is correct) but in the 2d viewer they're in different positions and they are outside the grey matter and the slide itself

<img width="1424" alt="Screenshot 2022-08-03 at 13 26 51" src="https://user-images.githubusercontent.com/57769656/182597044-012e3570-033a-438e-ab80-713c9f89e300.png">

**Comment by neuroBazzi** [comment]
@afonsobspinto Zoran clarified that issue 137 (that was the previous presentation of this problem) was deployed on stage so this is a new presentation of a similar phenomenon, could you please take a look at it when you have time. thank you!

**Comment by afonsobspinto** [comment]
@neuroBazzi I'm not able to replicate the issue with either of the V1_Calbindin_CordX_Data I have. Could you provide me the files you used to create the pink population?

![image](https://user-images.githubusercontent.com/19196034/186191241-639ab4ac-cc52-4131-b1f8-c7f00d2760d4.png)

**Comment by afonsobspinto** [comment]
PB: 
>no because it's an experiment I found there. I did not create it

me: 
>Ok, what I'm thinking is that the registration of that population might have been done so late in the past that it mismatches with the latest updates on the atlas.
