### ISSUE TITLE
Make population UI similar to Figma with colored dots preceding the label text

### ISSUE THREAD

**Issue by vidhya-metacell** [MetaCell/salk-interactive-atlas#19]
<img width="201" alt="Screen Shot 2022-02-28 at 12 44 34 PM" src="https://user-images.githubusercontent.com/71261494/155985728-e42b9724-4a58-4ae8-b720-1de181b8c537.png">

Please create a branch from feature/16 branch.

Current UI
<img width="226" alt="Screen Shot 2022-02-28 at 12 44 43 PM" src="https://user-images.githubusercontent.com/71261494/155985840-af2cce77-de0a-41a8-9b38-29a80066f280.png">

**Comment by paularah** [comment]
are the colours on the dots assigned randomly?

**Comment by vidhya-metacell** [comment]
@ddelpiano could you answer this one

> are the colours on the dots assigned randomly?

**Comment by ddelpiano** [comment]
> are the colours on the dots assigned randomly?

@paularah yes
