### ISSUE TITLE
Add "Powered by Metacell badge and link to metacell.us

### ISSUE THREAD

**Issue by mleiwe** [MetaCell/salk-interactive-atlas#224]
Ask Paul for help providing a suitable badge. Make sure there is a link behind it too

**Comment by neuroBazzi** [comment]
@zsinnema Paul added the logo in the 'about' modal. I am not sure we have enough time to create the modal. I see two main options:
1) If we have time to create the modal: Remove the 'about mouse cord atlas' paragraph and use only the Instigator and Funder. Change Instigator to Investigator. 
2) If we do not have time to build the modal, let's just put the badge 'power by MetaCell with logo' in the main page, replacing the 'Learn More' (which would also give us more visibility). 

thoughts? 

mockups are [here](https://www.figma.com/proto/sWj9a09BlfZknccnGqTLnV/Salk-Mouse-Cord-Atlas?node-id=876%3A3884&scaling=min-zoom&page-id=40%3A392&starting-point-node-id=317%3A2825&show-proto-sidebar=1)

![Image](https://user-images.githubusercontent.com/57769656/200258600-69d35603-39e1-4dae-8c04-d78927feec46.png)

**Comment by zsinnema** [comment]
@afonsobspinto do you have time?

**Comment by zsinnema** [comment]
@afonsobspinto here are the svgs

![Image](https://user-images.githubusercontent.com/124044/200615662-be17f4cc-8fa2-4df0-808e-8ff8c4168101.svg)
![Image](https://user-images.githubusercontent.com/124044/200615661-328ccc67-d90a-4f9f-afc6-3f7a84a2108e.svg)

**Comment by zsinnema** [comment]
@mleiwe @neuroBazzi deployed on staging. can you please test/check the whole application and let me know if this version can go to production.

**Comment by mleiwe** [comment]
@zsinnema for salk.metacell.us all the links on the bottom-left (Community, Help Center, and Learn More) don't seem to go anywhere or produce a pop up

**Comment by neuroBazzi** [comment]
@mleiwe we have not developed those yet, it is expected

**Comment by zsinnema** [comment]
@mleiwe did you test it on the staging server (https://salk.stage.metacell.us)?

**Comment by mleiwe** [comment]
Will try now, didn't know the address

**Comment by zsinnema** [comment]
@mleiwe @neuroBazzi please try to cover the whole application during the testing

**Comment by mleiwe** [comment]
Ok, the staging one works fine.

**Comment by zsinnema** [comment]
@neuroBazzi @mleiwe deployed on prod
