### ISSUE TITLE
Create a QR code that links to the Prod environment

### ISSUE THREAD

**Issue by mleiwe** [MetaCell/salk-interactive-atlas#229]

**Comment by mleiwe** [comment]
Could also link to the experiment in question too

**Comment by neuroBazzi** [comment]
https://www.salk.metacell.us/

**Comment by zsinnema** [comment]
https://www.qr-code-generator.com/

**Comment by neuroBazzi** [comment]
![QR2 (1)](https://user-images.githubusercontent.com/57769656/200780746-f05e2e44-ed75-489e-8c32-fbd733cc6da0.png)
![QR4 (1)](https://user-images.githubusercontent.com/57769656/200780753-456f02f4-99e1-44e8-858e-5ff9ba1f02b1.png)
![QR3 (1)](https://user-images.githubusercontent.com/57769656/200780760-18539b33-d0c0-4dd0-9c24-e376c2b0cc32.png)
![Qr1 (1)](https://user-images.githubusercontent.com/57769656/200780764-227a6d72-f1bb-4e31-9722-5eb3004dae8b.png)
