### ISSUE TITLE
"Rotate Z" and "Rotate MZ" don't function

### ISSUE THREAD

**Issue by mleiwe** [MetaCell/salk-interactive-atlas#232]
In the 3D view these two buttons don't seem to make any visual difference to the 3D view.

![Screen Shot 2022-11-09 at 5 14 13 PM](https://user-images.githubusercontent.com/29621219/200791305-42ffa961-b7f2-4fb9-9191-cdfe1a8e002b.png)

**Comment by zsinnema** [comment]
see: https://github.com/MetaCell/geppetto-meta/issues/327
