### ISSUE TITLE
Rename populations from the web application interface

### ISSUE THREAD

**Issue by neuroBazzi** [MetaCell/salk-interactive-atlas#256]
Request from user is to be able to change the population name from the UI inside in the experiment
<img width="221" alt="Screenshot 2023-04-13 at 19 15 11" src="https://user-images.githubusercontent.com/57769656/231835195-e385b46a-dbe2-49fd-b378-dd838ecc5caa.png">

@zsinnema could you please estimate? 

They are asking to be able to edit the name of the population from inside the experiment (see picture, they want to change V3 into something else). I think this would not require FE (maybe the rename is triggered double click on the name to change it) but it would require BE as the next time that the user logs in the new name should be displayed. Let's assume people can only change the name of the populations of experiments that they own (i.e. they created) and that everybody else who can see the experiment (because it has been shared with them) will see the new name too.

**Comment by afonsobspinto** [comment]
We would need to:
- Change the text field to an input text upon double click.
- Add a new view (PATCH) to allow populations to change the name if the user has the necessary rights and the name is valid.
- If the request fails (not enough permissions or invalid name) we keep the original name and potentially show a snackbar explaining why it failed.

Invalid names can be for example a population with the same name as one of its siblings or containing forbidden characters like @ 

Would probably be better to do after we address https://github.com/MetaCell/salk-interactive-atlas/issues/284

<details>
  <summary> I would estimate something around</summary>
  18 hours
</details>
