### ISSUE TITLE
Investigate Napari as replacement for their analysis

### ISSUE THREAD

**Issue by neuroBazzi** [MetaCell/salk-interactive-atlas#287]
@stephenlenzi They would like to know if they can sue Napari to analyse their data and to generate the input files. 
Could you please:
1) Get clarity from them (I guess Sofia mainly) about what their analysis is;
2) See if there is a combination of plugins that it would allow to do what they want
3) Estimate how long it would take for you to write plugins to 'fill in the gaps'

**Comment by stephenlenzi** [comment]
Just to clarify as my memory is patchy - is this to replace build a brain?
We'd really need to see their code or have a detailed list of steps in order to estimate this correctly

**Comment by neuroBazzi** [comment]
ok, yes this is to replace build a brain.

**Comment by neuroBazzi** [comment]
@stephenlenzi deprioritised, please do not work on this

**Comment by neuroBazzi** [comment]
Deprioritised by the client
