### ISSUE TITLE
Hierarchy design for subpopulation should be visible when accordion is open. Instead it shows on Hover.

### ISSUE THREAD

**Issue by D-GopalKrishna** [MetaCell/salk-interactive-atlas#323]
Video demo:

https://github.com/MetaCell/salk-interactive-atlas/assets/59233227/da514023-c6bd-41c3-8281-8d98998088e6

**Comment by afonsobspinto** [comment]
Ops I missed that you created the issue. I'm closing this one right now and we keep tracking it in #328. Thanks again.
